/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-26 12:34:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\" class=\"footer\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row g-5\">\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <h3 class=\"footer-heading\">About ZenBlog</h3>\r\n");
      out.write("            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab, perspiciatis beatae autem deleniti voluptate nulla a dolores, exercitationem eveniet libero laudantium recusandae officiis qui aliquid blanditiis omnis quae. Explicabo?</p>\r\n");
      out.write("            <p><a href=\"about.html\" class=\"footer-link-more\">Learn More</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-6 col-lg-2\">\r\n");
      out.write("            <h3 class=\"footer-heading\">Navigation</h3>\r\n");
      out.write("            <ul class=\"footer-links list-unstyled\">\r\n");
      out.write("              <li><a href=\"index.html\"><i class=\"bi bi-chevron-right\"></i> Home</a></li>\r\n");
      out.write("              <li><a href=\"index.html\"><i class=\"bi bi-chevron-right\"></i> Blog</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Categories</a></li>\r\n");
      out.write("              <li><a href=\"single-post.html\"><i class=\"bi bi-chevron-right\"></i> Single Post</a></li>\r\n");
      out.write("              <li><a href=\"about.html\"><i class=\"bi bi-chevron-right\"></i> About us</a></li>\r\n");
      out.write("              <li><a href=\"contact.html\"><i class=\"bi bi-chevron-right\"></i> Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-6 col-lg-2\">\r\n");
      out.write("            <h3 class=\"footer-heading\">Categories</h3>\r\n");
      out.write("            <ul class=\"footer-links list-unstyled\">\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Business</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Culture</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Sport</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Food</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Politics</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Celebrity</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Startups</a></li>\r\n");
      out.write("              <li><a href=\"category.html\"><i class=\"bi bi-chevron-right\"></i> Travel</a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <h3 class=\"footer-heading\">Recent Posts</h3>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"footer-links footer-blog-entry list-unstyled\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"single-post.html\" class=\"d-flex align-items-center\">\r\n");
      out.write("                  <img src=\"/home/img/post-sq-1.jpg\" alt=\"\" class=\"img-fluid me-3\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <div class=\"post-meta d-block\"><span class=\"date\">Culture</span> <span class=\"mx-1\">&bullet;</span> <span>Jul 5th '22</span></div>\r\n");
      out.write("                    <span>5 Great Startup Tips for Female Founders</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"single-post.html\" class=\"d-flex align-items-center\">\r\n");
      out.write("                  <img src=\"/home/img/post-sq-2.jpg\" alt=\"\" class=\"img-fluid me-3\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <div class=\"post-meta d-block\"><span class=\"date\">Culture</span> <span class=\"mx-1\">&bullet;</span> <span>Jul 5th '22</span></div>\r\n");
      out.write("                    <span>What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"single-post.html\" class=\"d-flex align-items-center\">\r\n");
      out.write("                  <img src=\"/home/img/post-sq-3.jpg\" alt=\"\" class=\"img-fluid me-3\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <div class=\"post-meta d-block\"><span class=\"date\">Culture</span> <span class=\"mx-1\">&bullet;</span> <span>Jul 5th '22</span></div>\r\n");
      out.write("                    <span>Life Insurance And Pregnancy: A Working Mom’s Guide</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"single-post.html\" class=\"d-flex align-items-center\">\r\n");
      out.write("                  <img src=\"/home/img/post-sq-4.jpg\" alt=\"\" class=\"img-fluid me-3\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                    <div class=\"post-meta d-block\"><span class=\"date\">Culture</span> <span class=\"mx-1\">&bullet;</span> <span>Jul 5th '22</span></div>\r\n");
      out.write("                    <span>How to Avoid Distraction and Stay Focused During Video Calls?</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-legal\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row justify-content-between\">\r\n");
      out.write("          <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("              © Copyright <strong><span>ZenBlog</span></strong>. All Rights Reserved\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"credits\">\r\n");
      out.write("              <!-- All the links in the footer should remain intact. -->\r\n");
      out.write("              <!-- You can delete the links only if you purchased the pro version. -->\r\n");
      out.write("              <!-- Licensing information: https://bootstrapmade.com/license/ -->\r\n");
      out.write("              <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->\r\n");
      out.write("              Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <div class=\"social-links mb-3 mb-lg-0 text-center text-md-end\">\r\n");
      out.write("              <a href=\"#\" class=\"twitter\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("              <a href=\"#\" class=\"facebook\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("              <a href=\"#\" class=\"instagram\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("              <a href=\"#\" class=\"google-plus\"><i class=\"bi bi-skype\"></i></a>\r\n");
      out.write("              <a href=\"#\" class=\"linkedin\"><i class=\"bi bi-linkedin\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"scroll-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/home/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/home/js/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/home/js/glightbox.min.js\"></script>\r\n");
      out.write("  <script src=\"/home/js/aos.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/home/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
